name: DeCoudre
version: ${pluginVersion}
description: ${properties.description}
author: syldium

main: me.syldium.decoudre.bukkit.DeCoudreBootstrap
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  dac:
    usage: /dac <join|leave> [args]

permissions:
  decoudre.admin:
    default: op
  decoudre.player:
    default: true
