name: Thimble
version: ${pluginVersion}
description: ${properties.description}
author: syldium

main: me.syldium.thimble.bukkit.ThBootstrap
api-version: 1.13
softdepend: [Parties, PlaceholderAPI, ViaVersion, WorldEdit]

commands:
  thimble:
    usage: /<command> help
    aliases: [th]
    permission: thimble.command

permissions:
  thimble.arena.*:
    default: op
    description: Grants access to commands to edit arenas.
    children:
      thimble.arena.create: true
      thimble.arena.set.gamemode: true
      thimble.arena.set.jump: true
      thimble.arena.set.max.players: true
      thimble.arena.set.min.players: true
      thimble.arena.set.spawn: true
  thimble.command:
    default: true
    description: Access to the main command.
  thimble.player.*:
    default: true
    description: Allows players to play in arenas.
    children:
      thimble.player.block: true
      thimble.player.join: true
      thimble.player.leave: true
  thimble.restrictions.bypass:
    description: Allows the in-game player to bypass commands restrictions.
    default: op
  thimble.sign.*:
    default: true
    description: Allows players to view statistics.
    children:
      thimble.sign.place: true
      thimble.sign.use: true
  thimble.stats.*:
    default: true
    description: Allows players to view statistics.
    children:
      thimble.stats: true
      thimble.stats.others: true
