name: Thimble
version: ${pluginVersion}
description: ${description}
website: https://github.com/syldium/Thimble
author: syldium

main: me.syldium.thimble.bukkit.ThBootstrap
api-version: 1.13
softdepend: [LuckPerms, Parties, PlaceholderAPI, ViaVersion, WorldEdit]

commands:
  thimble:
    usage: /<command> help
    permission: thimble.commands.base

permissions:
  thimble.commands.arena:
    default: op
    description: Grants access to commands to edit arenas.
    children:
      thimble.commands.arena.create: true
      thimble.commands.arena.set.gamemode: true
      thimble.commands.arena.set.jump: true
      thimble.commands.arena.set.max.players: true
      thimble.commands.arena.set.min.players: true
      thimble.commands.arena.set.spawn: true
      thimble.commands.arena.set.wait: true
      thimble.commands.arena.remove: true
  thimble.commands.base:
    default: true
    description: Access to the main command.
  thimble.commands.player:
    default: true
    description: Allows players to play in arenas.
    children:
      thimble.commands.player.block: true
      thimble.commands.player.join: true
      thimble.commands.player.leave: true
  thimble.restrictions.bypass:
    description: Allows the in-game player to bypass commands restrictions.
    default: op
  thimble.sign:
    default: true
    description: Allows players to view statistics.
    children:
      thimble.sign.place: true
      thimble.sign.use: true
  thimble.commands.stats:
    default: true
    description: Allows players to view statistics.
    children:
      thimble.commands.stats.others: true
  thimble.commands.reload:
    default: op
    description: Reload config files.
  thimble.commands.version:
    default: op
    description: Allows to use the /th version command.
    children:
      thimble.commands.version.update: true
