[versions]
adventure = "4.13.0"
adventurePlatform = "4.2.0"
annotations = "24.0.1"
jupiter = "5.9.2"
paper = "1.19.3-R0.1-SNAPSHOT"
sponge = "7.4.0"

[libraries]
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventurePlainSerializer = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
junitJupiter = { module="org.junit.jupiter:junit-jupiter-api", version.ref="jupiter" }
junitEngine = { module="org.junit.jupiter:junit-jupiter-engine" }
minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
paperBrigadier = { module = "io.papermc.paper:paper-mojangapi", version.ref = "paper" }
sponge = { module = "org.spongepowered:spongeapi", version.ref = "sponge" }

[bundles]
testDependencies = ["junitJupiter", "junitEngine"]
